# https://docs.codecov.com/docs/coverage-configuration
coverage:
  range: 70..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto    # the required coverage value
