name: build

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      - '.pre-commit-config.yaml'
      - 'codecov.yaml'
  pull_request_target:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      - '.pre-commit-config.yaml'
      - 'codecov.yaml'
  workflow_dispatch: { }
permissions: write-all
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      # limit parallel to avoid ip call limit
      max-parallel: 1
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12','3.11','3.10' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        run: |
          pip install poetry==1.7
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Install the project dependencies
        run: |
          poetry install
      - name: Pytest
        env:
          AliCloud_AK: ${{ secrets.AliCloud_AK }}
          AliCloud_SK: ${{ secrets.AliCloud_SK }}
          AliCloud_Account: ${{ secrets.AliCloud_Account }}
          AliCloud_TEST_DOMAIN: ${{ secrets.AliCloud_TEST_DOMAIN }}
          GH_PAT: ${{ secrets.GH_ADMIN_PAT }}
          GH_TEST_ORG: ${{ vars.GH_TEST_ORG }}
          GH_TEST_REPO: ${{ github.repository }}
        run: poetry run pytest --cov --cov-report json
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.python-version == '3.12'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  call_release_flow:
    needs: [ ci ]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/release.yaml
    secrets: inherit
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-secrets-to-nested-workflows
