name: Pre merge check
on:
  push:
    branches:
      - 'main'
  pull_request_target:
    branches:
      - 'main'
jobs:
  pre-merge-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if version already existed
        run: |
          pip install requests
          python .github/workflows/check-version.py