name: Pre merge check
on:
  push:
    branches:
      - 'main'
  pull_request_target:
    branches:
      - 'main'
jobs:
  pre-merge-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Check if version already existed
        run: |
          pip install requests >/dev/null
          python .github/workflows/check-version.py
